name: build

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
    
  pull_request:
    types: [opened, synchronize, reopened]  
  
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  build:
    runs-on: macos-13
    name: build
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1'
 
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
        
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'
      - uses: actions/download-artifact@v4
      - name: Download Artifacts
        run: ls -R
      
      - name: Setup Android & iOS Artifacts
        run: | 
          mkdir -p ${{ github.workspace }}/src/libpjsua2.so/org/pjsip
          mkdir -p ${{ github.workspace }}/src/pjsua2.maui.android/pjsua2
          mkdir -p ${{ github.workspace }}/src/libpjsua2.so/lib/arm64-v8a
          mkdir -p ${{ github.workspace }}/src/libpjsua2.so/lib/armeabi-v7a
          mkdir -p ${{ github.workspace }}/src/libpjsua2.so/lib/x86
          mkdir -p ${{ github.workspace }}/src/libpjsua2.so/lib/x86_64
          mv -v ${{ github.workspace }}/libpjsua2.maui.android/* ${{ github.workspace }}/src/pjsua2.maui.android/pjsua2
          rm -rf ${{ github.workspace }}/java/org/pjsip/pjsua2
          mv -v ${{ github.workspace }}/java/org/pjsip/* ${{ github.workspace }}/src/libpjsua2.so/org/pjsip/
          mv -v ${{ github.workspace }}/arm64-v8a/* ${{ github.workspace }}/src/libpjsua2.so/lib/arm64-v8a/
          mv -v ${{ github.workspace }}/armeabi-v7a/* ${{ github.workspace }}/src/libpjsua2.so/lib/armeabi-v7a/
          mv -v ${{ github.workspace }}/x86/* ${{ github.workspace }}/src/libpjsua2.so/lib/x86/
          mv -v ${{ github.workspace }}/x86_64/* ${{ github.workspace }}/src/libpjsua2.so/lib/x86_64/
          
          mkdir -p ${{ github.workspace }}/src/pjsua2.maui.ios/pjsua2
          mkdir -p ${{ github.workspace }}/src/libpjsua2.a/lib/arm64
          mkdir -p ${{ github.workspace }}/src/libpjsua2.a/lib/x86_64
          mv -v ${{ github.workspace }}/pjsua2maui/pjsua2/* ${{ github.workspace }}/src/pjsua2.maui.ios/pjsua2
          mv -v ${{ github.workspace }}/arm64/* ${{ github.workspace }}/src/libpjsua2.a/lib/arm64
          mv -v ${{ github.workspace }}/x86_64/* ${{ github.workspace }}/src/libpjsua2.a/lib/x86_64

      - name: Restore Dependencies
        run: | 
          dotnet restore src/pjsua2.maui.android/pjsua2.maui.android.csproj
          dotnet restore src/pjsua2.maui.ios/pjsua2.maui.ios.csproj

      - name: Build MAUI Android
        run: dotnet publish src/pjsua2.maui.android/pjsua2.maui.android.csproj -c Release -f net7.0-android --no-restore
       
      - name: Build MAUI iOS
        run: dotnet publish src/pjsua2.maui.ios/pjsua2.maui.ios.csproj -c Release -f net7.0-ios --no-restore
      
      - name: pack
        run: |
          cd ${{ github.workspace }}/src
          ./pack.sh