name: Build native libraries for Android

on:
  push:
    branches: [ main, develop ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
    
  pull_request:
    types: [opened, synchronize, reopened]  
  
  workflow_dispatch:

permissions:
  contents:   write  

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    
    - uses: actions/cache@v2
      id: cache-packages
      with:
        path: ${{ runner.temp }}/cache-linux
        key: cache-packages-v2.2

    - name: Prepare Environment
      uses: airvzxf/cache-anything-new-action@v1.0
      with:
        script: 'install.sh'
        is_cached: ${{ steps.cache-packages.outputs.cache-hit }}
        cache: ${{ runner.temp }}/cache-linux
      run: |
        cd ${{ github.workspace }}/android
        sudo ./prepare
    - name: Build openh264
      run: |
        cd ${{ github.workspace }}/android
        sudo ./openh264
    - name: Build openssl
      run: |
        cd ${{ github.workspace }}/android
        sudo ./openssl
    - name: Build opus
      run: |
        cd ${{ github.workspace }}/android
        sudo ./opus
    - name: Build pjsua2
      run: |
        cd ${{ github.workspace }}/android
        sudo ./build
    - name: Finalize
      run : |
        echo "done building"
    - name: Upload
      uses: actions/upload-artifact@v3
      with:
        name: lipjsua2.so
        path: /home/lib