name: release .nupkg's

on:
  push:
    tags: 
        '*' 
permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry
  PACKAGE_VERSION: '1.2.14.10'
jobs:
  build:
    runs-on: macos-13
    name: Build
    permissions:
      contents: write
    steps:
      - name: Setup Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.1'
 
      - name: Checkout
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: |
            7.0.x

      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources
        
      - uses: actions/setup-java@v2
        with:
          distribution: 'microsoft'
          java-version: '11'
      
      - name: Download Android & iOS Artifacts
        run: |
          echo "Android ..."
          curl -L -o ./libpjsua2.maui.so.tar.gz https://github.com/weslleymurdock/libpjsua2-android/releases/download/v1.0.0/libpjsua2.tar.gz
          tar -xzvf libpjsua2.maui.so.tar.gz 
          mkdir -p ${{ github.workspace }}/src/libpjsua2.so/org/pjsip
          mkdir -p ${{ github.workspace }}/src/pjsua2.maui.android/pjsua2
          mkdir -p ${{ github.workspace }}/src/libpjsua2.so/lib/
          mv -v ${{ github.workspace }}/home/runner/libpjsua2/lib/libpjsua2.maui.android/* ${{ github.workspace }}/src/pjsua2.maui/pjsua2
          rm -rf ${{ github.workspace }}/home/runner/libpjsua2/lib/java/org/pjsip/pjsua2
          mv -v ${{ github.workspace }}/home/runner/libpjsua2/lib/java/org/pjsip/* ${{ github.workspace }}/src/libpjsua2.so/org/pjsip/
          mv -v ${{ github.workspace }}/home/runner/libpjsua2/lib/* ${{ github.workspace }}/src/libpjsua2.so/lib/
          echo "iOS ..."
          curl -L -o ./libpjsua2.maui.a.tar.gz https://github.com/weslleymurdock/libpjsua2-ios/releases/download/v1.0.0/libpjsua2.tar.gz
          tar -xzvf libpjsua2.maui.a.tar.gz
          mkdir -p ${{ github.workspace }}/src/pjsua2.maui.ios/pjsua2
          mkdir -p ${{ github.workspace }}/src/libpjsua2.a/lib/
          mv -v ${{ github.workspace }}/libpjsua2/lib/pjsua2maui/pjsua2/* ${{ github.workspace }}/src/pjsua2.maui.ios/pjsua2
          mv -v ${{ github.workspace }}/libpjsua2/lib/* ${{ github.workspace }}/src/libpjsua2.a/lib/

      - name: Restore Dependencies
        run: | 
          dotnet restore src/pjsua2.maui.android/pjsua2.maui.android.csproj
          dotnet restore src/pjsua2.maui.ios/pjsua2.maui.ios.csproj

      - name: Build MAUI Android
        run: dotnet publish src/pjsua2.maui.android/pjsua2.maui.android.csproj -c Release -f net7.0-android --no-restore
       
      - name: Build MAUI Android
        run: dotnet publish src/pjsua2.maui.ios/pjsua2.maui.ios.csproj -c Release -f net7.0-ios --no-restore
      
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
            draft: false
            prerelease: false
            release_name: ${{ github.ref }}
            tag_name: ${{ github.ref }}
            body_path: CHANGELOG.md
        env: 
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: upload .nupkg 
        uses: actions/upload-release-asset@v1
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
            asset_path: ${{ github.workspace }}/src/libpjsua2.maui.${{ env.PACKAGE_VERSION }}.nupkg
            asset_name: libpjsua2.maui.${{ env.PACKAGE_VERSION }}.nupkg
            asset_content_type: application/zip